name: generic-dev

on:
  pull_request:
    branches: [ dev, master, actionsTest ]

jobs:

# Dev PR jobs that still have to be migrated from travis
#
# icc (need self-hosted)
# versionTag
# valgrindTest (keeps failing for some reason. need investigation)
# staticAnalyze (need trusty so need self-hosted)
# pcc-fuzz: (need trusty so need self-hosted)
# min-decomp-macros (flakey)
#
# setting up self-hosted is pretty straightforward, but
# I need admins permissions to the repo for that it looks like
# So I'm tabling that for now
#
# The master branch exclusive jobs will be in a separate
# workflow file (the osx tests and meson build that is)

  meson-msvc:
    name: 'Meson on Windows MSVC'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    # Some replacements:
    # * https://renenyffenegger.ch/notes/Windows/development/Visual-Studio/environment-variables/index
    # * https://github.com/microsoft/vswhere/wiki/Start-Developer-Command-Prompt
    - uses: ilammy/msvc-dev-cmd@v1

    - name: install meson
      run: |
        echo "$env:userprofile\AppData\Roaming\Python\Python37\Scripts" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
        pip install -U meson

    - run: |
        git clone https://github.com/lzutao/lz4/ third-party\lz4
        cd third-party\lz4
        git switch std
        meson setup `
          --buildtype=release `
          -Ddefault_library=shared `
          -Dprefix=C:\lz4 `
          contrib\meson builddir
        cd builddir
        meson compile
        meson install
        echo "PKG_CONFIG_PATH=C:\lz4\lib\pkgconfig" `
        | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: install zlib
      run: |
        vcpkg install --triplet x64-windows zlib
        echo "PKG_CONFIG_PATH=C:\vcpkg\packages\zlib_x64-windows\lib\pkgconfig;$env:PKG_CONFIG_PATH" `
        | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: install liblzma
      run: |
        vcpkg install --triplet x64-windows liblzma
        echo "CPPFLAGS=-IC:\vcpkg\packages\liblzma_x64-windows\include $env:CPPFLAGS" `
        | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8

    - name: test
      run: |
        cd build\meson
        meson setup `
            --buildtype=debugoptimized `
            -Db_lundef=false `
            -Dauto_features=enabled `
            -Dbin_programs=true `
            -Dbin_contrib=true `
            builddir
        meson compile -C builddir
