name: generic-dev

on:
  pull_request:
    branches: [ dev, master, actionsTest ]

jobs:

# Dev PR jobs that still have to be migrated from travis
#
# icc (need self-hosted)
# versionTag
# valgrindTest (keeps failing for some reason. need investigation)
# staticAnalyze (need trusty so need self-hosted)
# pcc-fuzz: (need trusty so need self-hosted)
# min-decomp-macros (flakey)
#
# setting up self-hosted is pretty straightforward, but
# I need admins permissions to the repo for that it looks like
# So I'm tabling that for now
#
# The master branch exclusive jobs will be in a separate
# workflow file (the osx tests and meson build that is)

  meson-msvc:
    name: 'Meson on Windows MSVC'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    # Some replacements:
    # * https://renenyffenegger.ch/notes/Windows/development/Visual-Studio/environment-variables/index
    # * https://github.com/microsoft/vswhere/wiki/Start-Developer-Command-Prompt
    - uses: ilammy/msvc-dev-cmd@v1

    - name: install meson
      run: |
        pip install -U meson

    - run: |
        git clone https://github.com/lzutao/lz4/ third-party\lz4
        cd third-party\lz4
        git switch std
        meson setup `
          --buildtype=release `
          -Ddefault_library=shared `
          -Dprefix=C:\lz4 `
          contrib\meson builddir
        cd builddir
        meson compile
        meson install

    - name: install zlib
      run: |
        vcpkg integrate install
        vcpkg install --triplet x64-windows zlib

    - name: install liblzma
      run: |
        vcpkg install --triplet x64-windows liblzma
        Tree C:\vcpkg\packages\liblzma_x64-windows /F

    - name: test
      run: |
        cd build\meson
        $env:CC = "gcc"
        $env:CXX = "g++"
        meson setup `
            --buildtype=debugoptimized `
            -Db_lundef=false `
            -Dauto_features=enabled `
            -Dbin_programs=true `
            -Dbin_contrib=true `
            -Ddefault_library=static `
            -Dpkg_config_path="C:\vcpkg\packages\zlib_x64-windows\lib\pkgconfig;C:\lz4\lib\pkgconfig" `
            -Dc_args="-IC:\vcpkg\packages\liblzma_x64-windows\include " `
            builddir
        meson compile -C builddir
